# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox"
  
  config.vm.define "web" do |s|
    s.vm.hostname = 'web'
    s.vm.box = "centos/7"
    s.vm.network :private_network, ip: "10.0.0.10"
    s.vm.provision :shell, :path => ".provision/bootstrap.sh"
  end

  config.vm.define "borg-client1" do |s|
    s.vm.hostname = 'borg-client1'
    s.vm.box = "centos/7"
    s.vm.network :private_network, ip: "10.0.0.11"
    s.vm.provision "shell", inline: <<-SHELL
    sudo yes "" | ssh-keygen
    SHELL
  end

  config.vm.provision "shell", inline: <<-SHELL
    sudo yum install -y epel-release wget
    sudo wget https://github.com/borgbackup/borg/releases/download/1.1.10/borg-linux64 -O /usr/local/bin/borg
    sudo chmod +x /usr/local/bin/borg
  SHELL

end
